language: c

notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
    skip_join: true

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make install
    - os: linux
      dist: bionic
      compiler: clang
      before_install:
        - sudo apt install libncursesw5-dev
      script:
        - make install
    - os: osx
      osx_image: xcode10.2
      script:
        - make install
