language: c

sudo: false

script:
 - ./configure
 - make all

notifications:
  irc:
    channels:
      - "irc.freenode.net#em.slashem.me"
    skip_join: true

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
